### ISSUE TITLE
Feature Request - name a Chart title

### ISSUE THREAD

**Issue by architaktus** [yet-another-tool/obsidian-findoc#10]
define a chart title like:

findoc
filename: ....
**title: my title**
model: income

**Comment by studiowebux** [comment]
Thanks !

Great Idea, 
I will take a look to all Feature Requests opened and try to organize and release a couple together

**Comment by studiowebux** [comment]
Hello
I released v0.5.3 and 0.5.4 that includes this feature, and started to work on v0.6.0 and tested the feature successfully.

You can update the plugin in Obsidian, 
I will close this ticket, do not hesitate to reopen if you have comments
