### ISSUE TITLE
Feature Request - make CSV Row reorderable

### ISSUE THREAD

**Issue by architaktus** [yet-another-tool/obsidian-findoc#11]
make them movable (i.e. a reorderable list component) like: 
![grafik](https://github.com/yet-another-tool/obsidian-findoc/assets/10756799/b1a55a31-ce3b-4de7-a61f-2c39ee03c17c)

**Comment by studiowebux** [comment]
Hello !

I made a small PR #16 

I used buttons to move up and down and replace the text for icons

**Comment by studiowebux** [comment]
Hello
I released v0.5.3 and 0.5.4 that includes this feature, and started to work on v0.6.0 and tested the feature successfully.

You can update the plugin in Obsidian, 
I will close this ticket, do not hesitate to reopen if you have comments
