### ISSUE TITLE
Feature Request - editing in CSV: inherit 

### ISSUE THREAD

**Issue by architaktus** [yet-another-tool/obsidian-findoc#12]
**Issue**: I am tired to defining the types/ID by adding a new one.

### Suggestion:
inherit the former type/ID by adding a new row.

_maybe also a switcher in setup for configuring this ?_

**Comment by studiowebux** [comment]
Hello !

I've started a branch with this feature, so far I've done:

- Autocomplete using existent IDs
- Added Duplicate Button to append an existing entry at the end
- Added a toggle option to either use the last item in the table (or not) when clicking on `add new row

TODO:

- Take a look to update the type when we use the autocomplete.

I will do more tests and review a couple of edge cases, then I will create a small release only for that feature.

**Comment by studiowebux** [comment]
Hello
I released v0.5.3 and 0.5.4 that includes this feature, and started to work on v0.6.0 and tested the feature successfully.

You can update the plugin in Obsidian, 
I will close this ticket, do not hesitate to reopen if you have comments
