### ISSUE TITLE
Feature Request - New Type

### ISSUE THREAD

**Issue by architaktus** [yet-another-tool/obsidian-findoc#13]
Manage data for the charts in csv is really a GREAT idea! And it wil be even better to extend its function to a general use (Annual development and so on) which means:
- the unit is not necessarily USD, and
- a new "General" type in csv is needed: whose chart similar to "income", but the unit (of both time and Data Points) could be defined.--- or even better when:
-  **types could be added/deleted/edited in configuration.**

**Comment by studiowebux** [comment]
Hello,

I've started working on v0.6.0, 
it includes a refactoring, and few more changes, 

Here are those related to this feature:

- You can now specify the chart label : **money**, **percent**, **generic** (no suffix), **custom** (You can specify the unit you want for prefix)
- I renamed the `types` for `categories` (I will also improve the documentation in this regard) and `id` is now `subcategory`
- For the Time, this one is tricky, I built everything around it. But I was able to implement a custom `splitBy` that takes other field ( I only tested the EXTRA field ) and it was able to group them by what is available in that field. I didn't go further
- **Categories** (_Types_) can be added and updated in the settings tab

Do you have an example or a small dataset with the expected output to provide?
this way I will see if I can make it work, and know what is required to either rework or adapt

I'm also reworking the models approach, my goal is to provide a more dynamic way to define functions that prepare and show the data.

**Comment by studiowebux** [comment]
Hello, 

I merged v0.6.0

Due to breaking changes, you have to overwrite the data.json file (Instruction here: https://studiowebux.github.io/obsidian-plugins-docs/docs/findoc/defaultConfigurations/)

Please feel free to reopen the ticket if there is anything
