### ISSUE TITLE
Feature Request - Sum of all

### ISSUE THREAD

**Issue by StrayaJake** [yet-another-tool/obsidian-findoc#7]
Would be great to have a option to enable a sum of all inside a category

Ie, Income, if I keep adding each month $4000, after a few months i would see 16000 in the graph not the $4000

**Comment by studiowebux** [comment]
Hello !

I created a PR with the addition of a new chart to do a cumulative sum #17

**Comment by studiowebux** [comment]
Hello
I released v0.5.3 and 0.5.4 that includes this feature.

I've started few days ago the v0.6.0, I'm refactoring the code to provide a configurable way to create models (the functions used to prepare and show the data)

You can update the plugin in Obsidian, 
I will close this ticket, do not hesitate to reopen if you have comments
